<?php

namespace App\Enums;

enum KaizenNotificationType: string
{
    case SUBMITTED_FOR_REVIEW = 'SUBMITTED_FOR_REVIEW';
    case APPROVAL_STAGE_READY = 'APPROVAL_STAGE_READY';
    case REVISION_REQUESTED = 'REVISION_REQUESTED';
    case REJECTED = 'REJECTED';
    case APPROVED = 'APPROVED';
    case IMPLEMENTATION_ASSIGNED = 'IMPLEMENTATION_ASSIGNED';
    case IMPLEMENTATION_STARTED = 'IMPLEMENTATION_STARTED';
    case IMPLEMENTATION_COMPLETED = 'IMPLEMENTATION_COMPLETED';
}
